# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='displayed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
