# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_idea_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='source',
            field=models.URLField(null=True),
        ),
    ]
