# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160426_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anon', max_length=32),
        ),
    ]
