# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160426_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
