# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160426_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.CharField(default='anon', max_length=32),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
