# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_comment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
