# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:23
from __future__ import unicode_literals

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_idea_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='skype',
            field=base.fields.SkypeField(max_length=32, null=True),
        ),
    ]
