# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:39
from __future__ import unicode_literals

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_idea_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='telegram',
            field=base.fields.TelegramField(max_length=33, null=True),
        ),
    ]
